### ISSUE TITLE
is this still being update? i get error: ./music_auto_eq:203:in `BigDecimal': can't convert nil into BigDecimal (TypeError)

### ISSUE THREAD

**Issue by droideggs** [kivikakk/music_auto_eq#1]
Here is the error I get

./music_auto_eq:203:in `BigDecimal': can't convert nil into BigDecimal (TypeError)
	from ./music_auto_eq:203:in `block in <main>'
	from ./music_auto_eq:203:in `map'
	from ./music_auto_eq:203:in `<main>'

**Comment by droideggs** [comment]
i spoke too soon. i fixed it by removing the Preamp line. interestingly after I removed that line in the txt file it still was able to calculate the preamp value. 

latest fixedbandeq.txt files have a line like this (this is for airpods pro 2 transparency mode)

Preamp: -3.2 dB
Filter 1: ON PK Fc 31 Hz Gain 1.7 dB Q 1.41
Filter 2: ON PK Fc 62 Hz Gain 2.8 dB Q 1.41
Filter 3: ON PK Fc 125 Hz Gain 1.0 dB Q 1.41
Filter 4: ON PK Fc 250 Hz Gain -1.5 dB Q 1.41
Filter 5: ON PK Fc 500 Hz Gain -2.8 dB Q 1.41
Filter 6: ON PK Fc 1000 Hz Gain 0.0 dB Q 1.41
Filter 7: ON PK Fc 2000 Hz Gain 0.8 dB Q 1.41
Filter 8: ON PK Fc 4000 Hz Gain 2.1 dB Q 1.41
Filter 9: ON PK Fc 8000 Hz Gain 1.1 dB Q 1.41
Filter 10: ON PK Fc 16000 Hz Gain -2.6 dB Q 1.41

**Comment by kivikakk** [comment]
Strange, the code filters out the preamp line:

https://github.com/kivikakk/music_auto_eq/blob/4a769e165b7963ec917f03980605807a823333d1/music_auto_eq#L203

Maybe there's a BOM, empty line or something else it wasn't expecting.

> is there a way to add custom EQ preset on iOS (iphone) ?

I wish! But I believe not.
